[package]
name = "gorkitale"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-rich-presence = "1.0.0"
tetra = "0.9.1"
rand = "0.9.2"
video-rs = { version = "0.10.5", features = ["ndarray"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

